name: Update ProjectV2 Single Select Field Option for Item
description: This action update the value of the single select option associated to the provided item id

inputs:
  pat_token:
    description: GitHub PAT token
    required: true
  organization:
    description: Organization login name
    required: true
  project_id:
    description: ProjectV2 Node ID
    required: true
  item_id:
    description: ProjectV2 Item ID
    required: true
  single_select_field_id:
    description: ProjectV2 Single Select Field ID
    required: true
  single_select_option_id:
    description: ProjectV2 Single Select Field Option ID
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.pat_token }}
        script: |
          const project_id = "${{ inputs.project_id }}";
          const item_id = "${{ inputs.item_id }}";
          const field_id = "${{ inputs.single_select_field_id }}";
          const option_id = "${{ inputs.single_select_option_id }}";

          const mutation = `
            mutation {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: "${project_id}",
                  itemId: "${item_id}",
                  fieldId: "${field_id}",
                  value: {
                    singleSelectOptionId: "${option_id}"
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }
          `;

          await github.graphql(mutation);
